# Generated by Django 4.1.7 on 2023-05-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=64)),
                ('average_price', models.IntegerField(blank=True, null=True, verbose_name='均价')),
                ('recommend', models.CharField(blank=True, max_length=128, null=True)),
                ('picture', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='商户头像')),
            ],
        ),
    ]
