# Generated by Django 4.1.7 on 2023-05-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='picture',
            field=models.ImageField(blank=True, default='/merchant_default.jpg', null=True, upload_to='', verbose_name='商户头像'),
        ),
    ]
