# Generated by Django 4.1.7 on 2023-05-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_merchant_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
