# Generated by Django 4.1.7 on 2023-05-12 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_merchant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
