# Generated by Django 4.1.7 on 2023-05-12 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_merchant_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='average_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='平均评分'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_hours',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='营业时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='environment_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='环境评分'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='server_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='服务评分'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='taste_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='味道评分'),
        ),
    ]
