# Generated by Django 4.1.7 on 2023-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_merchant_average_score_merchant_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='special',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='特色'),
        ),
    ]
