# Generated by Django 4.1.7 on 2023-05-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_merchant_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='average_score',
            field=models.FloatField(blank=True, null=True, verbose_name='平均评分'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='environment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='环境评分'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='server_score',
            field=models.FloatField(blank=True, null=True, verbose_name='服务评分'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='taste_score',
            field=models.FloatField(blank=True, null=True, verbose_name='味道评分'),
        ),
    ]
