# Generated by Django 4.1.7 on 2023-05-14 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_user_avatar'),
        ('app01', '0007_alter_merchant_average_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['create_time'], 'verbose_name': '商家', 'verbose_name_plural': '商家'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('comment_picture_one', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片评论1')),
                ('comment_picture_second', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片评论2')),
                ('comment_picture_third', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片评论3')),
                ('comment_auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='评论者')),
                ('commented_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.merchant', verbose_name='被评论商家')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['publish_time'],
            },
        ),
    ]
