# Generated by Django 4.1.7 on 2023-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_merchant_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='environment_score',
            field=models.CharField(blank=True, choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分')], max_length=32, null=True, verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='comment',
            name='server_score',
            field=models.CharField(blank=True, choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分')], max_length=32, null=True, verbose_name='服务'),
        ),
        migrations.AddField(
            model_name='comment',
            name='taste_score',
            field=models.CharField(blank=True, choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分')], max_length=32, null=True, verbose_name='味道'),
        ),
    ]
