# Generated by Django 4.1.7 on 2023-05-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_user_avatar'),
        ('app01', '0009_comment_environment_score_comment_server_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('collect_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='收藏用户')),
                ('collected_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.merchant', verbose_name='被收藏商家')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['collect_time'],
            },
        ),
    ]
