# Generated by Django 4.1.7 on 2023-05-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_collection_collect_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collected_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.merchant', verbose_name='被收藏商家'),
        ),
    ]
