# Generated by Django 4.1.7 on 2023-05-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_user_avatar'),
        ('app01', '0012_alter_collection_collected_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collect_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='收藏用户'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collected_merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.merchant', verbose_name='被收藏商家'),
        ),
    ]
