# Generated by Django 4.1.7 on 2023-05-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_user_avatar'),
        ('app01', '0013_alter_collection_collect_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collect_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='收藏用户'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collected_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.merchant', verbose_name='被收藏商家'),
        ),
    ]
