# Generated by Django 4.1.7 on 2023-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_comment_comment_auther_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='shop_name',
            field=models.CharField(max_length=128),
        ),
    ]
