# Generated by Django 4.1.7 on 2023-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_merchant_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='collect_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='收藏人数'),
        ),
    ]
