# Generated by Django 4.1.7 on 2023-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='data',
            field=models.CharField(default='2023/4/11 16:13:28', max_length=32),
            preserve_default=False,
        ),
    ]
