# Generated by Django 4.1.7 on 2023-04-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_userinfo_age_userinfo_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='data',
            new_name='datetime',
        ),
    ]
