# Generated by Django 4.1.7 on 2023-04-25 07:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_user_username_user_name_user_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='图片路径'),
        ),
    ]
