# Generated by Django 4.1.7 on 2023-05-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
