# Generated by Django 4.1.7 on 2023-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/default.jpg', null=True, upload_to='', verbose_name='图片路径'),
        ),
    ]
